apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  annotations:
    manifestival: new
  name: hcp-appsody-build-deploy-pl
  namespace: kabanero
spec:
  params:
    - description: The event type
      name: event-type
      type: string
    - description: The event ref
      name: event-ref
      type: string
    - name: target-namespace
      type: string
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: build-push-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
        outputs:
          - name: docker-image
            resource: docker-image
          - name: git-source
            resource: git-source
      taskRef:
        kind: Task
        name: hcp-appsody-build-push-task
    - name: deploy-task
      resources:
        inputs:
          - from:
              - build-push-task
            name: git-source
            resource: git-source
          - name: docker-image
            resource: docker-image
      params:
        - name: target-namespace
          value: $(params.target-namespace)
      runAfter:
        - build-push-task
      taskRef:
        kind: Task
        name: hcp-appsody-deploy-task
